struct operatorInfo operatorsArray[] ={ { "+",      opADD,    "#ffd1d1ff" },
                                        { "-",      opSUB,    "#66a5f2ff" },
                                        { "*",      opMUL,    "#ff950aff" },
                                        { "/",      opDIV,    "#8751ecff" },
                                        { "^",      opPOW,    "#eff482ff" },
                                        { "sin",    opSIN,    "#7cade8ff" },
                                        { "cos",    opCOS,    "#7adba6ff" },
                                        { "tg",     opTG,     "#9882dfff" },
                                        { "ctg",    opCTG,    "#e8c653ff" },
                                        { "arcsin", opARCSIN, "#b6cfedff" },
                                        { "arccos", opARCCOS, "#c3ebcaff" },
                                        { "arctg",  opARCTG,  "#e3daf8ff" },
                                        { "arcctg", opARCCTG, "#efce85ff" },
                                        { "sh",     opSH,     "#fb2020ff" },
                                        { "ch",     opCH,     "#586cf3ff" },
                                        { "th",     opTH,     "#d52ae8ff" },
                                        { "cth",    opCTH,    "#c96d22ff" },
                                        { "ln",     opLN,     "#ffffffff" },
                                        { "log",    opLOG,    "#ffd1f5ff" },
                                        { "exp",    opEXP,    "#2aec40ff" } };

const size_t NUM_OF_OPERATORS = sizeof(operatorsArray) / sizeof(operatorInfo);
